## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,vaini,TO,75.36,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
1,6,rikitea,PF,77.83,clear sky,-23.1203,-134.9692,People ThankYou
2,14,mahebourg,MU,78.26,scattered clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
3,21,iaciara,BR,82.26,overcast clouds,-14.0958,-46.6317,Hotel Matinha
4,25,georgetown,MY,82.33,few clouds,5.4112,100.3354,Cititel Penang

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}°F</dd>
"""


# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)
# 4b. Display the figure
fig = gmaps.figure(center = (30.0,31.0), zoom_level = 1.5)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Mexico selected country
mexico_df= vacation_df.loc[vacation_df['Country'] == 'MX']
mexico_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
48,163,tecoanapa,MX,83.17,few clouds,16.5167,-98.7500,Hotel Manglares
74,246,mina,MX,84.22,clear sky,26.0011,-100.5299,Mina ctl
77,254,cabo san lucas,MX,76.60,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
81,283,lazaro cardenas,MX,82.71,few clouds,17.9583,-102.2000,quinta antigua
117,433,acapulco,MX,84.65,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
167,653,miraflores,MX,75.02,clear sky,19.2167,-98.8083,Hotel Mansión

In [6]:
four_cities_df = mexico_df.loc[[81,117,48,167]]
four_cities_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
81,283,lazaro cardenas,MX,82.71,few clouds,17.9583,-102.2000,quinta antigua
117,433,acapulco,MX,84.65,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
48,163,tecoanapa,MX,83.17,few clouds,16.5167,-98.7500,Hotel Manglares
167,653,miraflores,MX,75.02,clear sky,19.2167,-98.8083,Hotel Mansión

In [7]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "miraflores"]
vacation_end = vacation_df.loc[vacation_df["City"] == "miraflores"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "lazaro cardenas"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "acapulco"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "tecoanapa"]

In [8]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [9]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
city_itinerary = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')

fig.add_layer(city_itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,653,miraflores,MX,75.02,clear sky,19.2167,-98.8083,Hotel Mansión
1,283,lazaro cardenas,MX,82.71,few clouds,17.9583,-102.2000,quinta antigua
2,433,acapulco,MX,84.65,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
3,163,tecoanapa,MX,83.17,few clouds,16.5167,-98.7500,Hotel Manglares
4,653,miraflores,MX,75.02,clear sky,19.2167,-98.8083,Hotel Mansión

In [11]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} </dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]

fig = gmaps.figure()

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))